name: Build

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  determine_changes:
    name: Determine changes
    runs-on: ubuntu-latest
    outputs:
      source: ${{ steps.determine.outputs.source }}
      container: ${{ steps.determine.outputs.container }}
      test: ${{ steps.determine.outputs.test }}
      project: ${{ steps.determine.outputs.project }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run change detection
        id: determine
        uses: ./.github/actions/determine-changes
#        with:
#          base-ref: ${{ github.event.pull_request.base.ref }}
#          head-ref: ${{ github.event.pull_request.head.ref }}

  build-oci-image:
    name: Build OCI image
    needs: determine_changes
    runs-on: ubuntu-latest
    permissions: write-all
    if: |
      github.event.pull_request.draft == false
      && (
        needs.determine_changes.outputs.project == true
        || needs.determine_changes.outputs.source == true
        || needs.determine_changes.outputs.container == true
      )
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build-container
        with:
          user: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
