name: Publish Python Package

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/build-container
        with:
          user: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            dev-requirements.txt

      - name: Install build tools
        run: |
          pip install -r dev-requirements.txt

      - name: Extract version from tag
        id: version
        run: |
          TAG=${GITHUB_REF##*/}
          echo "PACKAGE_VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
