name: Test and build

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: [ "main" ]
    paths:
      - lib/**
      - test/**
      - main.py
      - Dockerfile
      - requirements.txt
  pull_request:
    branches: [ "main" ]
    paths:
      - lib/**
      - test/**
      - main.py
      - Dockerfile
      - requirements.txt
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test-and-build:
    name: "Test and build"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
#      - name: Set up Python
#        uses: actions/setup-python@v3
#        with:
#          python-version: "3.13"
#          cache: "pip"
#      - run: pip install -r requirements.txt -r test-requirements.txt
#      - name: Run tests
#        env:
#          PYTHONPATH: "."
#        run: |
#          pytest --junitxml=test-results/tests.xml test
#      - name: Publish test results
#        uses: EnricoMi/publish-unit-test-result-action@v2
#        if: always()
#        with:
#          files: |
#            test-results/**/*.xml
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
