name: Test and build

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: [ "main" ]
    paths:
      - lib/**
      - test/**
      - main.py
      - Dockerfile
      - requirements.txt
  pull_request:
    branches: [ "main" ]
    paths:
      - lib/**
      - test/**
      - main.py
      - Dockerfile
      - requirements.txt
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test-and-build:
    name: "Test and build"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./test/docker-compose.yml"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            dev-requirements.txt
      - run: pip install -r requirements.txt -r dev-requirements.txt
      - name: Run tests
        env:
          PYTHONPATH: "."
        run: |
          pytest --junitxml=test-results/tests.xml test
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml
      - uses: ./.github/actions/build-container
        with:
          user: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
